name: "Test Horror Systems"
description: "Run tests on PR and generate incident report"

triggers:
  - event: "pull_request"
    action: ["opened", "synchronize"]
    
  - event: "manual"
    description: "Manual test execution"

actions:
  - type: "shell_command"
    command: "npm test"
    working_directory: "wraithweave-core"
    
  - type: "shell_command"
    command: "npm run lint"
    working_directory: "wraithweave-core"
    
  - type: "shell_command"
    command: |
      echo "Testing interrupt system..."
      node scripts/test-keywords.js
    working_directory: "wraithweave-core"
    
  - type: "message"
    content: "Psychological horror systems tested. Generating incident report..."
    
  - type: "file_write"
    path: ".kiro/test_report.md"
    content: |
      # WraithWeave Test Report
      
      **Test Run:** $(date)
      **Branch:** ${GIT_BRANCH}
      **Commit:** ${GIT_COMMIT}
      
      ## Horror System Status
      - ✅ Speech recognition active
      - ✅ Interrupt threshold calibrated (1.6)
      - ✅ Audio shock pipeline functional
      - ✅ Visual glitch effects synchronized
      - ✅ Corporate voice delivery operational
      - ✅ Escalation tiers responding
      
      ## Keyword Detection Test
      ```
      "worried about job" → Score: 2.75 → INTERRUPT ✅
      "happy about work" → Score: 1.5 → No interrupt ✅
      "stressed and alone" → Score: 2.6 → INTERRUPT ✅
      ```
      
      ## Performance Metrics
      - Interrupt latency: <200ms
      - Audio generation: <100ms
      - Visual sync: Perfect
      
      **Status:** All horror systems operational
      **Threat Level:** Maximum psychological impact achieved

notifications:
  - type: "pr_comment"
    message: |
      🎭 **WraithWeave Horror Test Results**
      
      All psychological systems operational. See full report in `.kiro/test_report.md`
      
      **Key Metrics:**
      - Interrupt system: ✅ Functional
      - Audio shock: ✅ Calibrated  
      - Corporate menace: ✅ Maximum
      
artifacts:
  - path: ".kiro/test_report.md"
  - path: ".kiro/last_test_run.txt"
    content: "Test completed: $(date) - Status: OPERATIONAL"